# Iterators and Generators

[TOC]


<!-- todo: add https://developers.google.com/web/fundamentals/primers/async-functions
 -->
 <!-- todo: split out Iterators and Generators from Async Functions -->

## Iterator

- object that has a `next()` method which returns a tuple object with a `value` and `done` property
- used to produce a sequence of values, can be any sequence, finite or infinite, unlike an array ❗️
- `value`: current value of the sequence, can be omitted when `done` is `true` or be the final return value
- `done`: `false` if there is another value in the sequence, else `true`
- can be created using using IIFE and closure to have internal state variables

```javascript
// infinite sequence
const counter = (function() {
    let id = 0;

    return {
        next() {
            id += 1;
            return { value: id, done: false };
        }
    };
})();

console.log(counter.next()); // { value: 1, done: false }
console.log(counter.next()); // { value: 2, done: false }
// ...
```

```javascript
// finite sequence
const it = (function() {
    let num = 0;

    return {
        next() {
            if (num < 10) {
                return { value: num++, done: false };
            } else {
                return { value: 10, done: true };
            }
        }
    };
})();

console.log(it.next()); // { value: 0, done: false }
console.log(it.next()); // { value: 1, done: false }
// ...
console.log(it.next()); // { value: 9, done: false }
console.log(it.next()); // { value: 10, done: true }
// ...
```

```javascript
// range [start, end)
function rangeMaker(start = 0, end = Infinity, step = 1) {
    let nextIndex = start;
    let iterationCount = 0;

    return {
        next: function() {
            let result;
            if (nextIndex < end) {
                result = { value: nextIndex, done: false };
                nextIndex += step;
                iterationCount++;
            }
            return result || { done: true };
        }
    };
}

const range = rangeMaker(0, 10);

console.log(range.next()); // { value: 0, done: false }
console.log(range.next()); // { value: 1, done: false }
// ...
console.log(range.next()); // { value: 9, done: false }
console.log(range.next()); // { done: true }
// ...
```

```javascript
// infinite sequence
const fibonacci = (function() {
    let n1 = 0;
    let n2 = 1;

    return {
        next() {
            const current = n1;
            n1 = n2;
            n2 = current + n2;

            return { value: current, done: false };
        }
    };
})();

console.log(fibonacci.next()); // { value: 0, done: false }
console.log(fibonacci.next()); // { value: 1, done: false }
// ...
```

- an iterator can only be consumed once, could however implement sequence to repeat itself ❗️



## Iterable

- object that has a method under the `Symbol.iterator` key that returns an iterator
- makes the object "iterable", defines its iteration behavior, e.g. in for...of loop, spread syntax, destructuring assignment, `yield*`, etc.
- many built-in APIs expect iterables, e.g. `Promise.all()`, `Promise.race()`, `Array.from()`, `new Map()`, `new Set()` and their "weak" counterparts, etc.
- the iterable's iterator is obtained through call to `Symbol.iterator` property, gives the values to be iterated, can iterate iterable as often as wants since `Symbol.iterator` returns new iterator
- `Symbol.iterator` is a unique computed property key
- beware: to access the iterable object using `this` from within the `next()` method on the iterator, must use an arrow function or fix `this` outside in the `Symbol.iterator` method, e.g. using `that = this` ❗️
- beware: values for which `done` is `true` don't show up in the iteration sequence, e.g. in for...of loop, spread syntax, destructuring assignment, etc. ❗️
- many built-in iterables, have `Symbol.iterator` property on their prototype chain, e.g. `String`, `Array`, `Map` and `Set`, but not `Object` ❗️

```javascript
const arr = [1, 2, 3, 4, 5];

for (const val of arr) {
    console.log(val); // 1 2 3 4 5
}
```

- can overwrite iteration behavior of built-in iterables by putting `Symbol.iterator` property on instance

```javascript
const arr = [1, 2, 3, 4, 5];

arr[Symbol.iterator] = function() {
    let i = 0;
    const maxIndex = this.length - 1;

    return {
        next: () => {
            if (i <= maxIndex) {
                return { value: this[maxIndex - i++], done: false };
            } else {
                return { done: true };
            }
        }
    };
};

for (const val of arr) {
    console.log(val); // 5 4 3 2 1
}
```

- implemented iteration sequence doesn't need to make sense, as long as `Symbol.iterator` returns a valid iterator

```javascript
const p = {
    names: ["Peter", "John", "Lisa"],
    [Symbol.iterator]() {
        let i = 0;
        let length = this.names.length;

        return {
            next: () => {
                if (i < length) {
                    return { value: this.names[i++], done: false };
                } else {
                    return { done: true };
                }
            }
        };
    }
};

for (const val of p) {
    console.log(val); // Peter John Lisa
}
```

- useful to make an iterator also an iterable by implementing the `Symbol.iterator` method returning itself

```javascript
const it = {
  next() { /* ... */ },
  [Symbol.iterator]() { return this; }
}
```



## Generator function

- "function" that looks like can pause and later resume where left of, return multiple values in between
- returns a generator object (think for now an iterator object), i.e. doesn't execute its "body" when called ❗️
- can use `yield` keyword in body, specifies next value in iteration sequence, looks like intermediary return
- uses function syntax, simply append `*` after function name

```javascript
function* gen() {
    const a = 21;
    yield a;
    const b = a * 2;
    yield b;
}

const it = gen();

console.log(it.next()); // { value: 21, done: false }
console.log(it.next()); // { value: 42, done: false }
console.log(it.next()); // { value: undefined, done: true }
// ..
```

- removes all the boilerplate to create iterator, also `yield` automatically wraps value in tuple object
- under the hood is wrapper to create iterators, can be thought of as returning instance of `Generator` with `next()` method containing big switch statement of body with a case for each section until the next `yield`, closed over state contains any shared variables and a counter for case of switch statement, i.e. not really a function
- beware: calling `next()` after iteration sequence is done continues with tuple `{ value: undefined, done: true }`
- beware: don't read like an ordinary function as if body is executed to completion, may yield out from infinite loop, just read like steps from one `yield` to next `yield` ❗️
- beware: doesn't start executing its "body" until generator object's `next()` is called

```javascript
function* gen() {
    let id = 0;

    while (true) {
        yield id;
        id += 1;
    }
}

const counter = gen();

console.log(counter.next()); // { value: 1, done: false }
console.log(counter.next()); // { value: 2, done: false }
// ...
```

- in loop can yield and increment later instead of saving current value temporarily while incrementing and then returning, because generator function "continues where it left off"

```javascript
function* gen() {
    let n1 = 0;
    let n2 = 1;

    while (true) {
        yield n1;
        n1 = n2;
        n2 = current + n2;
    }
}

const fibonacci = gen();

console.log(fibonacci.next()); // { value: 0, done: false }
console.log(fibonacci.next()); // { value: 1, done: false }
// ...
```

- generator object has a `Symbol.iterator` method returning itself, i.e. is also an iterable object, can use for...of loop, spread syntax, destructuring assignment, etc. ❗️

```javascript
// range [start, end)
function* gen(start = 0, end = Infinity, step = 1) {
    let i = start;

    while (i < end) {
        yield i
        i += step;
    }
}

const range = gen(0, 10);

for (const value of range) {
  console.log(value); // 0 1 ... 9
}

for (const value of gen(0, 10)) {
  console.log(value); // 0 1 ... 9
}
```

- can have `return` statement that ends iteration when it's reached, returns value with `done` set to `true`, i.e. won't show up in iteration sequence, if also wants last value to show up needs to yield it ❗️

```javascript
function* gen() {
    let num = 0;

    while (num < 10) {
        yield num;
        num += 1;
    }

    return 10;
}

const it = gen();

console.log(it.next()); // { value: 0, done: false }
console.log(it.next()); // { value: 1, done: false }
// ...
console.log(it.next()); // { value: 9, done: false }
console.log(it.next()); // { value: 10, done: true }
// ...

for (const value of it) {
  console.log(value); // 0 1 ... 9
}

console.log(...it); // 0 1 ... 9
```

- can make object iterable using simpler generator function syntax

```javascript
const o = {};

o[Symbol.iterator] = function*() {
    yield 21;
    yield 42;
};

for (const val of o) {
    console.log(val);
}
// 21
// 42
```

- can make all objects iterable by putting a generator function on the `Symbol.iterator` property of `Object.prototype`, can use the `Object.keys()` array to loop over property names, could also loop over array returned by `Object.entries()`

```javascript
// Note: properties added to the object after the iteration has begun are not visited, since the keys array is created at time of invoking the iteration
Object.prototype[Symbol.iterator] = function*() {
    const keys = Object.keys(this);

    for (const key of keys) {
        yield { key: key, val: this[key] };
    }
};

const o = { name: "Peter", age: 42 };

for (const v of o) {
    console.log(v);
}
// { key: 'name', val: 'Peter' }
// { key: 'age', val: 42 }
```

- an error not handled inside a generator function ends the iteration, i.e. calling `next()` returns tuple `{ value: undefined, done: true }` (given process didn't already exit because didn't handle error outside) ❗️

```javascript
function* gen() {
    yield 21;
    throw new Error("Nothing can pass me!");
    yield 42;
}

const it = gen();

console.log(it.next()); // { value: 21, done: false }
try {
    console.log(it.next());
} catch (e) {
    console.log("Handled error."); // Handled error.
}
console.log(it.next()); // { value: undefined, done: true }
```

- the `*` goes before the name in in ES6 method shorthand within object literal or class ❗️

```javascript
const key1 = "far";
const key2 = "boo";

const o = {
    name: "Peter",
    foo: function*() {},
    *bar() {},
    [key1]: function*() {},
    *[key2]() {}
};
```

- can not use `yield` in nested functions or callbacks, i.e. needs to loop imperatively, can't use `Array.prototype.forEach` etc., but can use inside argument position ❗️



## Generator (object)

- object returned by a generator function
- is both iterator and iterable since it has a `Symbol.iterator` method returning itself, but is even more
- can call `next()` with argument, resumes generator function replacing currently paused `yield` expression with argument  
  → allows for feedback, two-way communication, pull values out and push values in, looks like can influence function while it's running 🚀
- beware: argument to first `next()` call is ignored, since it only "starts" execution of generator function until first `yield`, i.e. `next()` call and the `yield` expression it replaces are offset by one, e.g. second `next()` call replaces first `yield` expression ⚠️

```javascript
function* gen() {
    const p = yield 1;
    yield p * 2;
}

const it = gen();

console.log(it.next());   // { value: 1, done: false }
console.log(it.next(21)); // { value: 42, done: false }
```

- can call `throw()` with argument, throws argument at current suspended `yield` position, ends iteration as if argument was thrown from within generator function

```javascript
function* gen() {
    yield 21;
    yield 42;
}

const it = gen();

console.log(it.next()); // { value: 21, done: false }
try {
    it.throw("Nothing can pass me!");
} catch (e) {
    console.log("Handled error."); // Handled error.
}
console.log(it.next()); // { value: undefined, done: true }
```



## Async iteration

- async code with promises is still not as nice as consecutive lines of sync code
- needs to juggle everything through promise chain, e.g. can't access values from earlier handlers without explicitly handing them through whole chain

```javascript
function asyncFn1(val1) {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res(val1 * 2);
        }, 1000);
    });
}

function asyncFn2(val2) {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res(val2 * 2);
        }, 1000);
    });
}

asyncFn1(10.5).then(asyncFn2).then(console.log).catch(console.log); // 42 
```

- combine generators and promises, generator function that yields promises
- consumer needs to pull promise from generator, resolve outside, push resolved value back inside, subsequent computations can use that value
- becomes nested promise chain, use helper function to recursively resolve promises, push resolved value back in iterator, and finally return promise with last value

```javascript
function spawn(iterator) {
    return new Promise((res, rej) => {
        (function onResult(previousValue) {
            const { value, done } = iterator.next(previousValue);
            if (!done) {
                value.then(onResult, rej);
            } else {
                res(value);
            }
        })();
    });
}

function* asyncFn(val1) {
    const val2 = yield asyncFn1(val1);
    const val3 = yield asyncFn2(val2);
    return val3;
}

spawn(asyncFn(10.5)).then(console.log).catch(console.log); // 42
```



## Async functions

- just sugar over async iteration, abstract away the helper function (with ES2017) 🚀
- use `async` before function name instead of `*`, `await` in function body instead of `yield`
- async code that looks like sync code, consecutive lines, no promise chains or callbacks, can use try...catch again 🚀
- non-blocking code is as easy as sync code 🚀

```javascript
async function asyncFn(val1) {
    const val2 = await asyncFn1(val1);
    const val3 = await asyncFn2(val2);
    return val3;
}

asyncFn(42).then(console.log).catch(console.log); // 42
```

- allows for sync code in between without needing to wrap in promise handler to make async and return implicit promise 🎉

```javascript
async function func() {
  const x = Promise.resolve(42);

  /* sync code here */

  return x;
}

func().then(console.log).catch(console.log); // 42
```

```javascript
const x = Promise.resolve(42);

x.then(data => { /* sync code here */ return data; }).then(console.log).catch(console.log); // 42    
```

- allows later handler to access the result from any earlier handler without the result needing to be carried through the entire promise chain, i.e. unwrap promise value and rewrap again at end in resolved promise even if didn't need value at all 🎉

```javascript
async function func() {
    const x = Promise.resolve(4);

    const y = (await x) / 2;

    return (await x) * y;
}

func().then(console.log).catch(console.log); // 8
```

```javascript
const x = Promise.resolve(4);

x.then(x => { return { x: x, y: x / 2 }; }).then(({ x, y }) => x * y).then(console.log); // 8
```

- looks like async function pauses until awaited promise has settled, i.e. can use result variable within sync code like normal sync code ❗️
- if expression is not a promise, it is converted to a resolved promise, i.e. `Promise.resolve(expr)`, then evaluated as value again
- beware: can not use `await` in nested functions or callbacks, similar to `yield`, but can use inside argument position ❗️
- async function returns implicit promise, resolves with `value` if function returns or rejects with `error` if function throws uncaught error
- `await` can only be used inside `async` function, evaluates as the value of the fulfilled promise or throws result of rejected promise, i.e. any unhandled rejected promises trickle up until most outer async function, must have a catch at least for the most outer async function so doesn't exit with `Unhandled promise rejection` ❗️
- beware: sync code after async function is run first before any awaited promise is resolved, since handlers are scheduled on microtask queue and async function just hides handlers that resolve awaited promises as seen in async iteration ❗️

```javascript
console.log("Start.");

(async function func() {
    const str = await Promise.resolve("Hello World!")
    console.log(str);
})().catch(console.log);

console.log("End.");

// Start.
// End.
// Hello World!
```

- inside the async function awaited promises block like sync code, if wants them to start concurrently or in parallel needs to await them later ❗️

```javascript
function oneSecond() {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res("Resolved fast.");
        }, 1000);
    });
}

function twoSeconds() {
    return new Promise((res, rej) => {
        setTimeout(() => {
            res("Resolved slow.");
        }, 2000);
    });
}
```

```javascript
async function sequential() {
    console.log("Starting promises sequentially...");

    const slow = await twoSeconds();
    console.log(slow);

    const fast = await oneSecond();
    console.log(fast);
}

sequential().catch(console.log);
// Starting promises sequentially... [0s since start]
// Resolved slow.                    [2s since start]
// Resolved fast.                    [3s since start]
```

```javascript
async function concurrent() {
    console.log("Starting promises concurrently...");

    const slow = twoSeconds();
    const fast = oneSecond();

    console.log(await slow);
    console.log(await fast);
}

concurrent().catch(console.log);
// Starting promises concurrently... [0s since start]
// Resolved slow.                    [2s since start]
// Resolved fast.                    [2s since start]
```

```javascript
function parallel() {
    console.log("Starting promises in parallel...");

    const slow = twoSeconds();
    const fast = oneSecond();

    slow.then(console.log).catch(console.log);
    fast.then(console.log).catch(console.log);
}

parallel();
// Starting promises in parallel... [0s since start]
// Resolved fast.                   [1s since start]
// Resolved slow.                   [2s since start]

// or as async function with error handling outside
async function parallel() {
    console.log("Starting promises in parallel...");

    const slow = twoSeconds();
    const fast = oneSecond();

    await Promise.all([
        (async() => {console.log(await slow);})(),
        (async() => {console.log(await fast);})()
    ]);
}

parallel().catch(console.log);
```

- in an async function `return`ing a promise and `return await`ing a promise is the same if the promise resolves, but if it rejects a `return` always returns the rejected promise, while an awaited promise throws and can be catched inside, if it is not catched it returns the rejected promise similarly to a `return`

```javascript
function failedPromise() {
    return new Promise((res, rej) => {
        setTimeout(() => {
            rej("Failed.");
        }, 1000);
    });
}
```

```javascript
async function func() {
    try {
        return failedPromise();
    } catch (err) {
        console.log("Handled error inside.");
    }
}

func().catch(err => { console.log("Handled error outside."); });
// Handled error outside.
```

```javascript
async function func() {
    try {
        return await failedPromise();
    } catch (err) {
        console.log("Handled error inside.");
    }
}

func().catch(err => { console.log("Handled error outside."); });
// Handled error inside.
```

- beware: can not stop async function in between `await`s, unlike generator function with custom helper function



## Summary

- iterator object: consumer can pull out multiple values from producer one at a time, consumer is in control, producer "waits" until consumer pulls next value, iterator is source
- generator object: consumer can push in multiple values to producer one at a time, consumer is in control, producer "waits" until consumer pulls next value, generator is sink, plus everything from iterator object since generator object is also iterator object



## Async generators

<!-- toDo: Finish, what does async function* () {} return ?? -->

- with ES2018
- can use `yield` and `await`
- can push out values asynchronously as they come

- normal async function gives back a single promise

- can't use for...of loop



## Async iterators

The Async Iteration introduces an AsyncIterator, which is similar to Iterator. The difference lies in the fact that the next, return, and throw methods of an AsyncIterator return a Promise for the iteration result, rather than the result itself.

An object that supports async iteration is said to be “iterable” if it has a Symbol.asyncIterator method that returns an AsyncIterator object.

for..await..of statement to iterate over an async iterable


## Resources

- MDN - as usual